const modal=document.querySelector('#modal'),steps=[...document.querySelectorAll('.modalstep')];let choice='';
function showModal(plan){modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';steps.forEach((s,i)=>s.style.display=i===0?'block':'none');if(plan){choice=plan;document.querySelector('.choices button[data-choice="Someone else"]').classList.add('selected');document.querySelector('.next').disabled=false}}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.open-modal').forEach(b=>b.onclick=()=>showModal(b.dataset.plan));document.querySelector('.close').onclick=closeModal;document.querySelector('.close2').onclick=closeModal;document.querySelector('.modalback').onclick=closeModal;
document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');choice=b.dataset.choice;document.querySelector('.next').disabled=false});
document.querySelector('.next').onclick=()=>{steps[0].style.display='none';steps[1].style.display='block'};document.querySelector('.back').onclick=()=>{steps[1].style.display='none';steps[0].style.display='block'};
document.querySelector('.finish').onclick=()=>{steps[1].style.display='none';steps[2].style.display='block';let n=document.querySelector('#firstName').value.trim();document.querySelector('#thanks').textContent=(n?`Thank you, ${n}. `:'Thank you. ')+`In a real launch, our care team would reach out personally about ${choice||'your family story'}. No information was submitted or saved.`};
document.querySelectorAll('.accordion article button').forEach(b=>b.onclick=()=>{let a=b.parentElement,was=a.classList.contains('open');document.querySelectorAll('.accordion article').forEach(x=>{x.classList.remove('open');x.querySelector('i').textContent='+'});if(!was){a.classList.add('open');b.querySelector('i').textContent='−'}});
document.querySelector('#playDemo').onclick=()=>{let t=document.createElement('div');t.className='toast';t.textContent='Sample conversation is being prepared • Preview coming soon';document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),400)},3500)};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
