const modal=document.querySelector('#modal'),steps=[...document.querySelectorAll('.modalstep')];let choice='';
function showModal(plan){modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';steps.forEach((s,i)=>s.style.display=i===0?'block':'none');if(plan){choice=plan;document.querySelector('.choices button[data-choice="Someone else"]').classList.add('selected');document.querySelector('.next').disabled=false}}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.open-modal').forEach(b=>b.onclick=()=>showModal(b.dataset.plan));document.querySelector('.close').onclick=closeModal;document.querySelector('.close2').onclick=closeModal;document.querySelector('.modalback').onclick=closeModal;
document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');choice=b.dataset.choice;document.querySelector('.next').disabled=false});
document.querySelector('.next').onclick=()=>{steps[0].style.display='none';steps[1].style.display='block'};document.querySelector('.back').onclick=()=>{steps[1].style.display='none';steps[0].style.display='block'};
document.querySelector('.finish').onclick=()=>{steps[1].style.display='none';steps[2].style.display='block';let n=document.querySelector('#firstName').value.trim();document.querySelector('#thanks').textContent=(n?`Thank you, ${n}. `:'Thank you. ')+`In a real launch, our care team would reach out personally about ${choice||'your family story'}. No information was submitted or saved.`};
document.querySelectorAll('.accordion article button').forEach(b=>b.onclick=()=>{let a=b.parentElement,was=a.classList.contains('open');document.querySelectorAll('.accordion article').forEach(x=>{x.classList.remove('open');x.querySelector('i').textContent='+'});if(!was){a.classList.add('open');b.querySelector('i').textContent='−'}});
const demoScreen=document.querySelector('#demoScreen'),caption=document.querySelector('#caption'),playButton=document.querySelector('#playDemo');
const defaultAnswer="Maine was our grand adventure. We packed sandwiches, took the long road along the coast, and laughed every time your grandfather missed a turn. The air smelled like pine and salt water. I still remember it clearly.";
let speaking=false;
function stopDemo(){if('speechSynthesis' in window)speechSynthesis.cancel();speaking=false;demoScreen.classList.remove('talking');playButton.classList.remove('playing');document.querySelectorAll('.questions button').forEach(x=>x.classList.remove('active'));caption.innerHTML='<span>Choose another memory to continue</span>'}
function speakAnswer(text,button){if(!('speechSynthesis' in window)){caption.innerHTML='<span>'+text+'</span>';demoScreen.classList.add('talking');setTimeout(stopDemo,7000);return}speechSynthesis.cancel();document.querySelectorAll('.questions button').forEach(x=>x.classList.remove('active'));if(button)button.classList.add('active');caption.innerHTML='<span>'+text+'</span><span class="voicebars"><i></i><i></i><i></i></span>';let u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/Samantha|Karen|Moira|Tessa|female/i.test(v.name))||voices.find(v=>/^en/i.test(v.lang))||null;u.rate=.88;u.pitch=1.05;u.volume=1;u.onstart=()=>{speaking=true;demoScreen.classList.add('talking');playButton.classList.add('playing')};u.onend=stopDemo;u.onerror=stopDemo;speechSynthesis.speak(u)}
playButton.onclick=()=>speaking?stopDemo():speakAnswer(defaultAnswer,document.querySelector('.questions button'));
document.querySelectorAll('.questions button').forEach(b=>b.onclick=()=>speakAnswer(b.dataset.answer,b));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
