const modal=document.querySelector('#modal'),steps=[...document.querySelectorAll('.modalstep')];let choice='';
function showModal(plan){modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';steps.forEach((s,i)=>s.style.display=i===0?'block':'none');if(plan){choice=plan;document.querySelector('.choices button[data-choice="Someone else"]').classList.add('selected');document.querySelector('.next').disabled=false}}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.open-modal').forEach(b=>b.onclick=()=>showModal(b.dataset.plan));document.querySelector('.close').onclick=closeModal;document.querySelector('.close2').onclick=closeModal;document.querySelector('.modalback').onclick=closeModal;
document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');choice=b.dataset.choice;document.querySelector('.next').disabled=false});
document.querySelector('.next').onclick=()=>{steps[0].style.display='none';steps[1].style.display='block'};document.querySelector('.back').onclick=()=>{steps[1].style.display='none';steps[0].style.display='block'};
document.querySelector('.finish').onclick=()=>{steps[1].style.display='none';steps[2].style.display='block';let n=document.querySelector('#firstName').value.trim();document.querySelector('#thanks').textContent=(n?`Thank you, ${n}. `:'Thank you. ')+`In a real launch, our care team would reach out personally about ${choice||'your family story'}. No information was submitted or saved.`};
document.querySelectorAll('.accordion article button').forEach(b=>b.onclick=()=>{let a=b.parentElement,was=a.classList.contains('open');document.querySelectorAll('.accordion article').forEach(x=>{x.classList.remove('open');x.querySelector('i').textContent='+'});if(!was){a.classList.add('open');b.querySelector('i').textContent='−'}});
const demoScreen=document.querySelector('#demoScreen'),caption=document.querySelector('#caption'),playButton=document.querySelector('#playDemo');
const defaultAnswer="Maine was our grand adventure. We packed sandwiches, took the long road along the coast, and laughed every time your grandfather missed a turn. The air smelled like pine and salt water. I still remember it clearly.";
let speaking=false;
function stopDemo(){if('speechSynthesis' in window)speechSynthesis.cancel();speaking=false;demoScreen.classList.remove('talking');playButton.classList.remove('playing');document.querySelectorAll('.questions button').forEach(x=>x.classList.remove('active'));caption.innerHTML='<span>Choose another memory to continue</span>'}
function speakAnswer(text,button){if(!('speechSynthesis' in window)){caption.innerHTML='<span>'+text+'</span>';demoScreen.classList.add('talking');setTimeout(stopDemo,7000);return}speechSynthesis.cancel();document.querySelectorAll('.questions button').forEach(x=>x.classList.remove('active'));if(button)button.classList.add('active');caption.innerHTML='<span>'+text+'</span><span class="voicebars"><i></i><i></i><i></i></span>';let u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/Samantha|Karen|Moira|Tessa|female/i.test(v.name))||voices.find(v=>/^en/i.test(v.lang))||null;u.rate=.88;u.pitch=1.05;u.volume=1;u.onstart=()=>{speaking=true;demoScreen.classList.add('talking');playButton.classList.add('playing')};u.onend=stopDemo;u.onerror=stopDemo;speechSynthesis.speak(u)}
playButton.onclick=()=>speaking?stopDemo():speakAnswer(defaultAnswer,document.querySelector('.questions button'));
document.querySelectorAll('.questions button').forEach(b=>b.onclick=()=>speakAnswer(b.dataset.answer,b));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));

const knowledge={
pricing:'EverPresent has four paths. Digital is $129 once plus $10 a month on any phone or browser. Companion is proposed at $249 plus $19 a month. Display starts at $999 plus $29–49 a month and includes a glasses-free 3D display. Concierge is $2,500–$5,000 for white-glove capture and setup.',
consent:'Consent comes first. The person whose face and voice are captured must understand and agree while living. The family controls access, can correct the archive, and can request permanent deletion at any time.',
privacy:'Your family space is private and invite-only. Family owners control access. EverPresent does not sell recordings or use them for advertising, and the family can request permanent deletion.',
companion:'EverPresent Companion is a proposed product for someone living with memory loss. A captured family member or friend provides a familiar face and voice between visits, guides reminiscence, and shares fresh photos, videos and messages from the family. It supports company and orientation; it is not medical treatment.',
display:'EverPresent Display starts at $999 plus $29–49 a month. It includes Digital access and a glasses-free light-field portrait display, so the presence can feel at home on a shelf or desk without a headset.',
digital:'Digital is the most affordable place to start: $129 once plus $10 a month. It works on a phone or browser, with guided remote capture, face, voice, conversation and a private family link. No hardware is required.',
concierge:'Concierge is a white-glove $2,500–$5,000 option with an in-home capture session, a dedicated story producer, family archive organization, custom display setup and priority support.',
start:'Start with a private preview. We learn whose story or presence you want to capture, confirm consent, recommend a plan and guide the first recording. This demo does not place an order or save your information.',
receive:'Your family receives a guided capture plan, a conversational presence, a private family space, family review before release, phone and browser access, and an optional glasses-free 3D display.',
record:'Capture can happen at home or remotely. We guide a relaxed conversation through childhood, family names, favorite sayings, recipes, values and messages for future generations. The person can skip anything.',
wrong:'If the presence does not know an answer, it should say so. EverPresent is designed to stay anchored to the real recordings and family archive, not invent memories.',
funeral:'Funeral homes are one future partner channel. EverPresent is also built for pre-need living capture, gifts from adult children, families and memory care facilities.',
plan:'For the lowest-cost start, choose Digital. For a loved one to provide familiar company between visits, explore Companion. For a physical 3D presence at home, choose Display. For full in-home service, choose Concierge.'};
function answerQuestion(q){let x=q.toLowerCase();if(/which|right|recommend|best plan/.test(x))return knowledge.plan;if(/price|cost|how much|tier/.test(x))return knowledge.pricing;if(/consent|permission|agree/.test(x))return knowledge.consent;if(/private|privacy|delete|data|secure/.test(x))return knowledge.privacy;if(/dementia|memory loss|companion|facility|care/.test(x))return knowledge.companion;if(/display|hologram|3d|headset|hardware/.test(x))return knowledge.display;if(/digital|phone|browser|afford/.test(x))return knowledge.digital;if(/concierge|white.glove|home capture/.test(x))return knowledge.concierge;if(/receive|included|get/.test(x))return knowledge.receive;if(/record|capture|session|interview/.test(x))return knowledge.record;if(/wrong|invent|know an answer|hallucin/.test(x))return knowledge.wrong;if(/funeral|market|channel/.test(x))return knowledge.funeral;if(/start|sign up|begin|next/.test(x))return knowledge.start;return 'The clearest answer depends on your family. Digital is the affordable phone and browser option, Companion brings a familiar loved one between visits, Display adds glasses-free 3D, and Concierge provides full service. Ask me about pricing, consent, privacy, capture, Companion or what happens next.'}
const askForm=document.querySelector('#askForm'),askInput=document.querySelector('#askInput'),messages=document.querySelector('#messages');
function addMessage(txt,who){let d=document.createElement('div');d.className='msg '+who;d.textContent=txt;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
function ask(q){if(!q.trim())return;addMessage(q,'user');let t=addMessage('Thinking…','bot thinking');setTimeout(()=>{t.classList.remove('thinking');t.textContent=answerQuestion(q)},450)}
askForm.addEventListener('submit',e=>{e.preventDefault();let q=askInput.value;askInput.value='';ask(q)});document.querySelectorAll('.ask-prompts button').forEach(b=>b.onclick=()=>{ask(b.textContent);document.querySelector('#ask').scrollIntoView({behavior:'smooth',block:'center'})});
